import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <ul className="flex gap-x-4 p-4">
            <li>
              <Link href="/">React Swiper</Link>
            </li>
            <li>
              <Link href="/embla-carousel">Embla Carousel</Link>
            </li>
            <li>
              <Link href="/react-slick">React Slick</Link>
            </li>
          </ul>
        </nav>
        <main >{children}</main>
      </body>
    </html>
  );
}
